#ifndef AQUA_BUILD_HEADER
#define AQUA_BUILD_HEADER

#ifndef NDEBUG
	#define AQUA_DEBUG 1
	#define AQUA_RELEASE 0
#else
	#define AQUA_DEBUG 0
	#define AQUA_RELEASE 1
#endif // !NDEBUG

#define AQUA_DEBUG_ENABLE_LOG      AQUA_DEBUG
#define AQUA_DEBUG_ENABLE_WARNINGS AQUA_DEBUG

#define AQUA_RELEASE_ENABLE_LOG      AQUA_RELEASE
#define AQUA_RELEASE_ENABLE_WARNINGS AQUA_RELEASE

#define AQUA_BUILD_TYPE_ENABLE_LOG \
	((AQUA_DEBUG && AQUA_DEBUG_ENABLE_LOG) || (AQUA_RELEASE && AQUA_RELEASE_ENABLE_LOG))
#define AQUA_BUILD_TYPE_ENABLE_WARNINGS \
	((AQUA_DEBUG && AQUA_DEBUG_ENABLE_WARNINGS) || (AQUA_RELEASE && AQUA_RELEASE_ENABLE_WARNINGS))

// ------------------------------------------ OpenGL ------------------------------------------

#define AQUA_OPENGL_VERSION_MAJOR 4
#define AQUA_OPENGL_VERSION_MINOR 5

#endif // !AQUA_BUILD_HEADER