#ifndef AQUA_PLATFORM_HEADER
#define AQUA_PLATFORM_HEADER

#if defined(WIN32) && WIN32
	#define AQUA_PLATFORM_WINDOWS 1
	#define AQUA_PLATFORM_LINUX 0
#endif // _WIN32

#if AQUA_PLATFORM_WINDOWS
	#define AQUA_LOGGER_CONSOLE_PROCESS_PATH "Logger.exe"
#endif // AQUA_PLATFORM_WINDOWS

#endif // !AQUA_PLATFORM_HEADER